/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model2(props) {
  const { nodes, materials } = useGLTF("kotiwca2.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials.Material}
        position={[0.166, -0.344, -0.091]}
        rotation={[1.014, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials.Material}
        position={[0.002, -0.443, -0.016]}
        rotation={[2.585, 0, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials.Material}
        position={[-0.049, -0.482, 0.005]}
        rotation={[-0.557, 0, -Math.PI]}
        scale={[-0.012, -0.131, -0.111]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials.Material}
        position={[0, 0, -0.004]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <group
        position={[-0.04, 0.822, -0.004]}
        rotation={[Math.PI, 0, Math.PI / 2]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_1.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_2.geometry}
          material={materials.Material}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/kotiwca2.glb");