/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { TextureLoader } from 'three/src/loaders/TextureLoader'
import { useLoader } from '@react-three/fiber'

export function Model2(props) {
    const { nodes, materials } = useGLTF("/kotiwca2.glb");
    const [colorMap, displacementMap, normalMap, roughnessMap, metalnessMap] = useLoader(TextureLoader, [
        'Metal046A_1K_Color.jpg',
        'Metal046A_1K_Displacement.jpg',
        'Metal046A_1K_NormalGL.jpg',
        'Metal046A_1K_Roughness.jpg',
        'Metal046A_1K_Metalness.jpg'
    
    
      ])
    return (
        <group {...props} dispose={null}>
            <mesh
                // castShadow
                // receiveShadow
                geometry={nodes.Plane.geometry}
                //material={materials["CW-Iron"]}
                position={[0.166, -0.344, -0.091]}
                rotation={[1.014, 0, Math.PI]}
            >
                <meshStandardMaterial
                map={colorMap}
                // displacementScale={1}
                // displacementMap={displacementMap}
                // normalMap={normalMap}
                // roughnessMap={roughnessMap}
                // roughness={1}
                // metalnessMap={metalnessMap}
                // metalness={0} 
                />

            </mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder.geometry}
                material={materials["CW-Iron"]}
                position={[0.002, -0.443, -0.016]}
                rotation={[2.585, 0, Math.PI / 2]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube001.geometry}
                material={materials["CW-Iron"]}
                position={[-0.049, -0.482, 0.005]}
                rotation={[-0.557, 0, -Math.PI]}
                scale={[-0.012, -0.131, -0.111]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube004.geometry}
                material={materials["CW-Iron"]}
                position={[0, 0, -0.004]}
                rotation={[Math.PI, 0, Math.PI]}
            />
            <group
                position={[-0.04, 0.822, -0.004]}
                rotation={[Math.PI, 0, Math.PI / 2]}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder004.geometry}
                    material={materials["CW steel"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder004_1.geometry}
                    material={materials["CW-Iron"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder004_2.geometry}
                    material={materials["CW-Aluminum-matte"]}
                />
            </group>
        </group>
    );
}

useGLTF.preload("/kotiwca2.glb");




